---
name: Bug report
about: Create a report to help us improve
title: ''
labels: 1-bug
assignees: ''

---

<!-- 
- Before submitting an issue please refer to https://lava-nc.org/developer_guide.html#how-to-contribute-to-lava.

- Please make sure you are posting an issue pertaining to the github.com/lava-nc/lava. For issues with lava libraries please file in the appropriate library repository, for example, github.com/lava-nc/lava-dl/issues.

- Please do not submit support requests or "How to" questions here, use discussions Q&A https://github.com/lava-nc/lava/discussions/categories/q-a

- ISSUES MISSING IMPORTANT INFORMATION MAY BE CLOSED WITHOUT INVESTIGATION. 
-->

**Describe the bug**
A clear and concise description of what the bug is.

**To reproduce current behavior**
Steps to reproduce the behavior:
1. When I run this code (add code or minimum test case) ...
```python
def my_code():
    pass
```
2. I get this error ...
```
Error...
```

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem. Remove section otherwise.

**Environment (please complete the following information):**
 - Device: [e.g. Laptop, Intel cloud]
 - OS: [e.g. Linux]
 - Lava version [e.g. 0.6.1]

**Additional context**
Add any other context about the problem here. Remove section otherwise.
